In [1]:
import torch
import numpy as np

In [2]:
np_data = np.arange(6).reshape((2,3))

## torch.from_numpy() &  torch_data.numpy()

In [3]:
torch_data = torch.from_numpy(np_data)

In [4]:
np_data

array([[0, 1, 2],
       [3, 4, 5]])

In [5]:
torch_data

tensor([[0, 1, 2],
        [3, 4, 5]])

In [6]:
tensor2array = torch_data.numpy()

In [7]:
tensor2array

array([[0, 1, 2],
       [3, 4, 5]])

## torch.FloatTensor()

In [8]:
data = [-1,-2,1,2]
tensor = torch.FloatTensor(data)

In [9]:
np.abs(data)

array([1, 2, 1, 2])

In [10]:
torch.abs(tensor)

tensor([1., 2., 1., 2.])

## np.matmul() & torch.mm()

In [17]:
data = [[1,2],[3,4]]
tensor = torch.FloatTensor(data)

In [12]:
np.matmul(data,data) # data.dot(data)

array([[ 7, 10],
       [15, 22]])

In [13]:
torch.mm(tensor,tensor)

tensor([[ 7., 10.],
        [15., 22.]])

In [16]:
torch.FloatTensor(np.array(data))

tensor([[1., 2.],
        [3., 4.]])

In [20]:
tensor.dot(tensor)

RuntimeError: dot: Expected 1-D argument self, but got 2-D

In [22]:
tensor = torch.FloatTensor(data.flatten())
tensor.dot(tensor)

tensor(30.)