In [1]:
import torch
from torch.autograd import Variable

In [2]:
tensor = torch.FloatTensor([[1,2],[3,4]])
variable = Variable(tensor,requires_grad=True)

In [3]:
tensor

tensor([[1., 2.],
        [3., 4.]])

In [5]:
variable

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [6]:
t_out = torch.mean(tensor*tensor)

In [7]:
t_out

tensor(7.5000)

In [12]:
v_out = torch.mean(variable*variable)

In [13]:
v_out

tensor(7.5000, grad_fn=<MeanBackward1>)

In [14]:
v_out.backward()
print(variable.grad)

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [15]:
variable.data

tensor([[1., 2.],
        [3., 4.]])

In [16]:
variable.data.numpy()

array([[1., 2.],
       [3., 4.]], dtype=float32)